# Generated by Django 4.0.1 on 2022-05-19 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='name',
            new_name='decision',
        ),
    ]
