# Generated by Django 4.0.1 on 2022-05-23 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0002_rename_name_application_decision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='decision',
            field=models.CharField(default='Pending', max_length=100),
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
