# Generated by Django 4.0.1 on 2022-05-30 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0003_alter_application_decision_alter_job_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='eligibility',
            field=models.TextField(),
        ),
    ]
